### ISSUE TITLE
RightIcon is not visible

### ISSUE THREAD

**Issue by rrsalian16** [fireship-io/229-multi-level-dropdown#15]
DropdownItems rightIcon is not visible

**Comment by starlightromero** [comment]
This has already been referenced in issue #5 

For ease I have included the below code:

```css
.icon-right svg {
  fill: var(--text-color);
  width: 20px;
  height: 20px;
}
```
