### ISSUE TITLE
Menu Chevrons don't display correctly in any browser

### ISSUE THREAD

**Issue by antiquechrono** [fireship-io/229-multi-level-dropdown#5]
The > icons in the menu fail to display correctly in any recent browser.

**Comment by olpner** [comment]
Same here

**Comment by BrChung** [comment]
This is because the class 'icon-right' is not set to any size, add this to your CSS file:

```css
.icon-right svg {
  fill: var(--text-color);
  width: 20px;
  height: 20px;
}
```
